// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC7qLGjQE_bLpaQTvMKu0UaGJim39kvrME',
    appId: '1:796300142656:web:9a963547e62f86073297a5',
    messagingSenderId: '796300142656',
    projectId: 'grocery-task-patrick',
    authDomain: 'grocery-task-patrick.firebaseapp.com',
    storageBucket: 'grocery-task-patrick.appspot.com',
    measurementId: 'G-ZW1SLMK6YQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBn6EJ4LNymH0OmVukC2um03m0v3XKLhXQ',
    appId: '1:796300142656:android:9bee0f12f9fccb6b3297a5',
    messagingSenderId: '796300142656',
    projectId: 'grocery-task-patrick',
    storageBucket: 'grocery-task-patrick.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCgfUcUnLgRAd04taGFIX_RleR-LI_tXT4',
    appId: '1:796300142656:ios:f250b6b6890689873297a5',
    messagingSenderId: '796300142656',
    projectId: 'grocery-task-patrick',
    storageBucket: 'grocery-task-patrick.appspot.com',
    iosBundleId: 'com.example.groceryTask',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCgfUcUnLgRAd04taGFIX_RleR-LI_tXT4',
    appId: '1:796300142656:ios:f68333e21f61aefd3297a5',
    messagingSenderId: '796300142656',
    projectId: 'grocery-task-patrick',
    storageBucket: 'grocery-task-patrick.appspot.com',
    iosBundleId: 'com.example.groceryTask.RunnerTests',
  );
}
